services:
  app:
    build: .
    container_name: yhlas-anomaly-detection
    ports:
      - "4086:4086"
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
